module.exports = {
  PHOTO_RECEIVED: "PHOTO_RECEIVED",
  PHOTOS_RECEIVED: "PHOTOS_RECEIVED",
  PHOTO_REMOVED: "PHOTO_REMOVED",
  ERRORS_RECEIVED: "ERRORS_RECEIVED",
  COMMENT_RECEIVED: "COMMENT_RECEIVED"
};
